### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by faruktoptas** [smartface/smartface.ui-editor#2]
I got the errors below when i try `npm install`

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ui-editor.explorer
npm ERR! 404
npm ERR! 404 'ui-editor.explorer' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@smartface/smartface.ui-editor'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by ozcanovunc** [comment]
Should be fixed right now, thanks for the report.

**Comment by faruktoptas** [comment]
Thanks `npm install` works, but I could not run it locally. How can I run?

**Comment by alperozisik** [comment]
@faruktoptas You do not run it locally. This is a Cloud IDE plugin already running as a part of the IDE.
NPM is for its installation purpose with the other modules. This not a standalone module.

**Comment by faruktoptas** [comment]
Thanks @alperozisik :)
I thought that it is standalone ui editor. You may specify it in a readme file.

**Comment by alperozisik** [comment]
@cenkce might consider it.
